[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/assessment"
  to = "https://tally.so/r/ZjNr5z"
  status = 302
  force = true

[[redirects]]
  from = "/assessment/"
  to = "https://tally.so/r/ZjNr5z"
  status = 302
  force = true
